Skip indexes on the local database, since even with the atlasAdmin role (or [backup, clusterMonitor, readAnyDatabase]) it fails on Atlas clusters with:
MongoServerError: not authorized on local to execute command { aggregate: "replset.minvalid", pipeline: [ { $indexStats: {} }, { $group: { _id: "$key", stats: { $push: { accesses: "$accesses.ops", host: "$host", since: "$accesses.since" } } } }, { $project: { key: "$_id", stats: 1, _id: 0 } } ], cursor: {}, apiVersion: "1", lsid: { id: UUID(<UUID>) }, $clusterTime: { clusterTime: Timestamp(1724256067, 1), signature: { hash: BinData(0, <HEX>), keyId: <NUM> } }, $db: "local" }